name: Publish Python Package with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read  # Only read access is required

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t acon-builder .

    - name: Test Docker image (optional)
      run: docker run --rm acon-builder

    - name: Copy built distribution files
      id: copy-files
      run: |
        docker create --name temp-container acon-builder
        docker cp temp-container:/usr/src/app/dist ./dist
        docker rm temp-container

    - name: Upload to PyPI using API Token
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
